Weblog.Web/Controllers/Site/BlogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Weblog.Core.Helpers;
using Weblog.Web.Models.Weblog;
using Weblog.Web.Services;
using WebMatrix.WebData;


namespace Weblog.Web.Controllers.Site
{
    public class BlogController : Controller
    {
        private IWeblogService _weblogService = new WeblogService();
        private ISettingsService _settingsService = new SettingsService();

        #region Views

        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult EditorialDepartment()
        {
            return View();
        }

        #region Entry
        [Authorize(Roles = "Administrator")]
        public ActionResult AddEntry()
        {
            AddEntryModel model = new AddEntryModel();
            model.CategoriesList = _weblogService.GetCategories();

            return View(model);
        }

        [HttpPost()]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Administrator")]
        [ValidateInput(false)] //html tags, will be removed,  newline will be <br/>
        public ActionResult AddEntry(AddEntryModel model)
        {
            if (ModelState.IsValid)
            {
                model.Text = InputFilterHelper.sanitizeInput(model.Text);
                this._weblogService.StoreEntry(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost()]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteEntry(int id)
        {
            this._weblogService.DeleteEntry(id);
            return RedirectToAction("Index");
        }

        public ActionResult DisplayEntry(String entryID)
        {
            int intEntry;
            if (entryID == null)
            {
                return RedirectToAction("Index", "Errors", null);
            }
            try
            {
                intEntry = Convert.ToInt32(entryID);
            }
            catch (System.FormatException)
            {
                return RedirectToAction("Index", "Errors", null);
            }

            EntryModel model = _weblogService.GetEntry(intEntry);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        #endregion

        #region Category
        [Authorize(Roles = "Administrator")]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost()]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Administrator")]
        public ActionResult AddCategory(AddCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                if (_weblogService.CategoryExists(model.Name))
                {
                    ModelState.AddModelError("", "Eine Kategorie mit dem gleichen Namen ist bereits vorhanden.");
                }
                else
                {
                    _weblogService.StoreCategory(model);
                    return RedirectToAction("AddCategory");
                }
            }
            return View();
        }

        [HttpPost()]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Administrator")]
        public JsonResult DeleteCategory(int id)
        {
            this._weblogService.DeleteCategory(id);
            return Json(new { success = true });
        }

        #endregion

        #endregion

        #region Partial Views

        #region Entry
        public ActionResult DisplayEntries()
        {
            List<EntryModel> entryList = this._weblogService.GetEntries();
            return displayEntriesByX(entryList);
        }

        public ActionResult DisplayEntriesByCategory(String id)
        {
            int categoryID;
            if (id == null)
            {
                return RedirectToAction("Index", "Errors", null);
            }
            try
            {
                categoryID = Convert.ToInt32(id);
            }
            catch (System.FormatException)
            {
                return RedirectToAction("Index", "Errors", null);
            }
            List<EntryModel> entryList = this._weblogService.GetEntriesByCategory(categoryID);
            return displayEntriesByX(entryList);
        }

        public ActionResult DisplayEntriesByDate(String month, String year)
        {
            List<EntryModel> entryList = new List<EntryModel>();
            int intMonth, intYear;
            if (month == null || year == null)
            {
                return RedirectToAction("Index", "Errors", null);
            }
            try
            {
                intMonth = Convert.ToInt32(month);
                intYear = Convert.ToInt32(year);
            }
            catch (System.FormatException)
            {
                return RedirectToAction("Index", "Errors", null);
            }

            try
            {
                entryList = this._weblogService.GetEntriesByDate(intMonth, intYear);
            }
            catch (System.ArgumentOutOfRangeException)
            {
                return RedirectToAction("Index", "Errors", null);
            }
            return displayEntriesByX(entryList);
        }

        private ActionResult displayEntriesByX(List<EntryModel> entryList)
        {
            DisplayEntriesPageModel entryPageModel = new DisplayEntriesPageModel(entryList);
            DisplayEntriesModel model = new DisplayEntriesModel(entryPageModel);
            return PartialView("DisplayEntries", model);
        }

        #endregion

        #region Category
        public ActionResult DisplayCategories()
        {
            List<CategoryModel> viewModel = this._weblogService.GetCategories();
            return PartialView("PartialViews/DisplayCategories", viewModel);
        }
        #endregion

        #region Comments

        public ActionResult DisplayCommentsForEntry(String id)
        {
            if (_settingsService.GetSiteSettings().AllowComments)
            {
                List<CommentModel> commentList;
                int entryID;
                if (id == null)
                {
                    return RedirectToAction("Index", "Errors", null);
                }
                try
                {
                    entryID = Convert.ToInt32(id);
                }
                catch (System.FormatException)
                {
                    return RedirectToAction("Index", "Errors", null);
                }

                commentList = _weblogService.GetCommentsForEntry(entryID);


                if (commentList.Count == 0)
                {
                    commentList = new List<CommentModel>();
                }
                return PartialView("PartialViews/DisplayCommentsForEntry", commentList);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult AddComment(String entryString)
        {
            if (_settingsService.GetSiteSettings().AllowComments)
            {
                int entryID;
                if (entryString == null)
                {
                    return RedirectToAction("Index", "Errors", null);
                }
                try
                {
                    entryID = Convert.ToInt32(entryString);
                }
                catch (System.FormatException)
                {
                    return RedirectToAction("Index", "Errors", null);
                }
                EntryModel entry = _weblogService.GetEntry(entryID);
                if (entry != null)
                {
                    AddCommentModel model = new AddCommentModel(entry);
                    return PartialView("PartialViews/AddComment", model);
                }
            }
            return RedirectToAction("Index");

        }

        [HttpPost()]
        [ValidateAntiForgeryToken()]
        [ValidateInput(false)] //html tags, will be removed,  newline will be <br/>
        public ActionResult AddComment(AddCommentModel model)
        {
            if (ModelState.IsValid)
            {
                if (!WebSecurity.IsAuthenticated)
                {
                    if (CaptchaHelper.CheckCaptcha(model.CaptchaResult))
                    {
                        model.Text = InputFilterHelper.sanitizeInput(model.Text);
                        this._weblogService.StoreComment(model);
                    }
                    else
                    {
                        ModelState.AddModelError("", "Das eingegebene Captcha ist leider falsch.");
                        return PartialView("PartialViews/AddComment", model);
                    }
                }
                else
                {
                    model.Text = InputFilterHelper.sanitizeInput(model.Text);
                    this._weblogService.StoreComment(model);
                }
            }
            return PartialView("PartialViews/AddComment", model);
        }

        [HttpPost()]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Administrator")]
        public JsonResult DeleteComment(int id)
        {
            this._weblogService.DeleteComment(id);
            return Json(new { success = true });
        }

        #endregion

        public ActionResult Categories()
        {
            List<CategoryModel> categoryList = _weblogService.GetCategories();
            return PartialView("PartialViews/Categories", categoryList);
        }

        public ActionResult Dates()
        {
            List<DateTime> dateList = _weblogService.GetDates();
            return PartialView("PartialViews/Dates", dateList);
        }

Weblog.Web/Controllers/Site/ViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Weblog.Web.Services;

namespace Weblog.Web.Controllers.Site
{
    public class ViewController : Controller
    {
        private ISettingsService _settingsService = new SettingsService();

        public String Keywords()
        {
            return _settingsService.GetSiteSettings().SiteKeywords;
        }

        public String Footer()
        {
            return _settingsService.GetSiteSettings().SiteFooterText;
        }

        public String Sitename()
        {
            return _settingsService.GetSiteSettings().SiteName;
        }
    }
}

Weblog.Web/Views/Blog/AddCategory.cshtml
@model Weblog.Web.Models.Weblog.AddCategoryModel

@{
    ViewBag.Title = "Kategorie hinzufügen";
}
<div class="blog-header">
    <h2>Kategorie hinzufügen</h2>
</div>

@using (Html.BeginForm("AddCategory", "Blog", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form">
        @Html.ValidationSummary()
        <div class="row form-group">
            @Html.LabelFor(m => m.Name, new { @class = "control-label col-sm-3" })
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
        <div class="row">
            <button class="btn btn-primary">Speichern</button>
        </div>
    </div>
}

@Html.Action("DisplayCategories")

Weblog.Web/Views/Blog/AddEntry.cshtml
@model Weblog.Web.Models.Weblog.AddEntryModel
@{
    ViewBag.Title = "Blogeintrag verfassen";
}

<div class="blog-header">
    <h2>Blogeintrag verfassen</h2>
</div>

@using (Html.BeginForm("AddEntry", "Blog", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ID)
    @Html.ValidationSummary()
    <div class="form">
        <div class="row form-group">
            @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-3" })
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
        </div>
        <div class="row form-group">
            @Html.LabelFor(m => m.Text, new { @class = "control-label col-sm-3" })
            @Html.TextAreaFor(m => m.Text, new { @class = "form-control" })
        </div>
        <div class="row categoryRow">

            @if (Model.CategoriesList.Count > 0)
            {
                for (int i = 0; i < Model.CategoriesList.Count; i++)
                {
                    <span class="form-group">

                        @Html.CheckBoxFor(model => model.CategoriesList[i].isElementsCategory)
                        @Html.LabelFor(model => model.CategoriesList[i].isElementsCategory, Model.CategoriesList[i].Name, new { @class = "control-label" })
                        @Html.HiddenFor(m => m.CategoriesList[i].Name)
                        @Html.HiddenFor(m => m.CategoriesList[i].ID)
                    </span>
                }
            }
        </div>
    </div>
    <div class="row">
        <button class="btn btn-primary">Speichern</button>
    </div>

}

Weblog.Web/Views/Blog/Categories.cshtml
@using Weblog.Web.Models.Weblog
@model List<CategoryModel>

@if (Model.Count > 0)
{
    <ol class="list-unstyled">
        @foreach (CategoryModel item in Model)
        {
            <li>
               @Ajax.ActionLink(item.Name, "DisplayEntriesByCategory", new { item.ID }, new AjaxOptions
           {
               UpdateTargetId = "displayEntries",
               InsertionMode = InsertionMode.Replace,
               HttpMethod = "GET",
               OnSuccess = "SiteHelpers.newPagination()"
           }, new { })
                   
            </li>
        }
    </ol>
}

Weblog.Web/Views/Blog/Dates.cshtml
@using Weblog.Web.Models.Weblog
@model List<DateTime>

@if (Model.Count > 0)
{
    <ol class="list-unstyled">
        @foreach (DateTime item in Model)
        {
            <li>
                @Ajax.ActionLink(item.ToString("MMMM yyyy"), "DisplayEntriesByDate", new { month = item.Month, year = item.Year }, new AjaxOptions
           {
               UpdateTargetId = "displayEntries",
               InsertionMode = InsertionMode.Replace,
               HttpMethod = "GET",
               OnSuccess = "SiteHelpers.newPagination()"
           }, new { })

            </li>
        }
    </ol>
}

Weblog.Web/Views/Blog/DisplayCategories.cshtml
@using Weblog.Web.Models.Weblog
@model List<CategoryModel>
@if (Model.Count > 0)
{
    <table class="table toDeleteIfEmpty">
        <tr>
            <th class="first">ID</th>
            <th>Name</th>
            @if (User.IsInRole("Administrator"))
            {
                <th>Löschen</th>
            }
        </tr>
        @foreach (CategoryModel item in Model)
        {
            String idString = "row" + item.ID;

            <tr id=@idString>
                <td>@item.ID</td>
                <td>@item.Name</td>
                @if (User.IsInRole("Administrator"))
                {
                    <td>
                        @using (Ajax.BeginForm(new AjaxOptions() { Url = "/Blog/DeleteCategory/" + @item.ID, OnSuccess = "SiteHelpers.deleteRow(" + @item.ID + ")" }))
                        {
                            @Html.AntiForgeryToken()
                            <button class="btn btn-danger">Löschen</button>
                        }
                    </td>
                }
            </tr>
        }
    </table>
}

Weblog.Web/Views/Blog/DisplayEntries.cshtml
@model Weblog.Web.Models.Weblog.DisplayEntriesModel

<div class="row">
    <div id="entry-container">
        @Html.Partial("PartialViews/DisplayEntriesPage", Model.EntryPerPageModel)
    </div>
</div>
<div class="row">
    <div id="pagination-container" data-entries-per-page="@Model.EntriesPerSite" data-last-page="@Model.LastPage">
        @if (Model.EntryPerPageModel.Entries.Count > Model.EntriesPerSite)
        {
            <ul class="pagination">
                <li id="pagination-previous" class="pagination-element">
                    <a href="#" onclick="EntryPagination.previousPage()">&laquo;</a>
                </li>

                @for (int i = 0; (i * Model.EntriesPerSite) < Model.EntryPerPageModel.Entries.Count; i++)
                {
                    <li id="pagination-@i" class="pagination-element">
                        <a href="#" onclick="EntryPagination.goToPage(@i)">@(i + 1)</a>
                    </li>
                }

                <li id="pagination-next" class="pagination-element">
                    <a href="#" onclick="EntryPagination.nextPage()">&raquo;</a>
                </li>
            </ul>
        }
    </div>
</div>

Weblog.Web/Views/Blog/DisplayEntry.cshtml
@model Weblog.Web.Models.Weblog.EntryModel

@{
    ViewBag.Title = "Einzelansicht";
}

<div class="blog-header">
    <h2>Einzelansicht</h2>
</div>

<div class="blog-post">
    <h2 class="blog-post-title">@Model.Title</h2>
    <p class="blog-post-meta">@Model.DateString von @Model.Author</p>

    <p>@Html.Raw(Model.Text)</p>
    <div class="categoryRow">
        @if (Model.Categories.Count > 0)
        {
            <br />
            <p class="blog-post-meta">Kategorien:</p>
            foreach (var item in Model.Categories)
            {
                <span>@item.Name </span>
            }
        }
    </div>
    @if (User.IsInRole("Administrator"))
    {
        using (Html.BeginForm("DeleteEntry", "Blog", new { Model.ID }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <br />
            <button class="btn btn-danger">Eintrag löschen</button>
        }
    }
</div>
@if (Model.AllowComments)
{
    <div id="displayCommentsForEntryDiv">
        @Html.Action("DisplayCommentsForEntry", new { id = Model.ID })
    </div>
    <br />
    <div id="addCommentDiv">
        @Html.Action("AddComment", new { entryString = Model.ID })
    </div>
}

Weblog.Web/Views/Blog/DisplayEntryPage.cshtml
@model Weblog.Web.Models.Weblog.DisplayEntryPageModel
@if (Model.Entries.Count > 0)
{
    for (int i = 0; i < Model.Entries.Count; i++)
    {
        var item = Model.Entries[i];

        <div class="blog-post entry">
            <h2 class="blog-post-title">@Html.ActionLink(item.Title, "DisplayEntry", "Blog", new { entryID = item.ID }, null)</h2>
            <p class="blog-post-meta">@item.DateString von @item.Author</p>

            @*
                i % Model.EntriesPerSite  um bei jeder Seite die Post von 0 bis EntriesPerSite zu sortieren.
                < FullEntriesPerSite schaut dann nur noch wie viele davon voll angezeigt werden dürfen
            *@
            @if (((i % Model.EntriesPerSite)) < Model.FullEntriesPerSite)
            {
                 <p>@Html.Raw(item.Text)</p>
            }
            else
            {
                 <p>@Html.Raw(item.TextShort)</p>
                if (item.TextShort.Length > item.textLength)
                {
                    @Html.ActionLink("mehr", "DisplayEntry", "Blog", new { entryID = item.ID }, null)
                }
            }
        </div>
    }
}
else
{
    <p>Hier könnten ihre Blogeinträge stehen.</p>
}

Weblog.Web/Views/Blog/EditorialDepartment.cshtml
@{
    ViewBag.Title = "Redaktionsbereich";
}

<div class="blog-header">
    <h2>Redaktionsbereich</h2>
</div>
<div class="row">
    <div class="col-sm-8 blog-main">
        <p>Die folgenden Links führen auf andere Seiten, auf denen dann die jeweiligen Vorgehensweisen sichtbar sind.</p>
        @Html.ActionLink("Neue Kategorie hinzufügen", "AddCategory", "Blog") - fügt eine neue Kategorie in der Datenbank hinzu<br />
        @Html.ActionLink("Neuen Eintrag hinzufügen", "AddEntry", "Blog") - fügt einen neuen Eintrag in der Datenbank hinzu<br /><br />
    </div>
</div>

Weblog.Web/Views/Blog/Index.cshtml
@{
    ViewBag.Title = @Html.Action("Sitename", "View");
}

<div class="blog-header">
    <h1 class="blog-title">@Html.Action("Sitename", "View")</h1>
</div>
<div class="row">
    <div class="col-sm-8 blog-main">
        <div id="displayEntries">
            @Html.Action("DisplayEntries")
        </div>
    </div>
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module sidebar-module-inset">
            @Html.Action("About")
        </div>
        <div class="sidebar-module">
            @Html.Action("Categories", "Blog")
        </div>
        <div class="sidebar-module">
            @Html.Action("Dates", "Blog")
        </div>
    </div>
</div>